# Generated by Django 4.2.6 on 2023-11-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='receipt_image_path',
            field=models.CharField(blank=True, max_length=277, null=True),
        ),
    ]
