# Generated by Django 4.2.6 on 2023-11-27 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0002_expense_receipt_image_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='item',
            new_name='store_name',
        ),
    ]
